 clc;clear;close;
Ws=linspace(-2,2,10000);
Wr=0.05;
Rs=100/4096;
Rr=81/4096;
Lm=5793/4096;
Lls=262/4096;
Llr=Lls;
Ls=Lm+Lls;
Lr=Lm+Llr;
Den=(Rr^2+((Ws-Wr).^2)*(Lr^2));
Zd=Rs+Ws.*(Ws-Wr)*(Lm^2)*Rr./Den;
Zq=Ws*Ls-Ws*Lr.*((Ws-Wr).^2)*(Lm^2)./Den;
Wsl=Ws-Wr;
figure(1);

ax1=subplot(2,2,1);
yyaxis(ax1,'left');
plot(ax1,Ws,Zd-Rs);
title('{\omega_r}=0.05,{R_r}=0.02');
xlabel('{\omega_s}');
ylabel('Z_d-R_s');
yyaxis(ax1,'right');
plot(ax1,Ws,Zq);
ylabel('Z_q');
grid on;

Wr=0.5;
% Den=(Rr^2+(Ws-Wr).^2*Lr^2);
% Zd=Rs+Ws.*(Ws-Wr)*Lm^2*Rr./Den;
% Zq=Ws*Ls-Ws*Lr.*(Ws-Wr).^2*Lm^2./Den;
Den=(Rr^2+((Ws-Wr).^2)*(Lr^2));
Zd=Rs+Ws.*(Ws-Wr)*(Lm^2)*Rr./Den;
Zq=Ws*Ls-Ws*Lr.*((Ws-Wr).^2)*(Lm^2)./Den;
ax1=subplot(2,2,2);
yyaxis(ax1,'left');
plot(ax1,Ws,Zd-Rs);
hold on;
plot(ax1,Ws,Zd);
title('{\omega_r}=0.5,{R_r}=0.02');
xlabel('{\omega_s}');
ylabel('Z_d-R_s');
yyaxis(ax1,'right');
plot(ax1,Ws,Zq);
ylabel('Z_q');
grid on;

Wr=1;
Den=(Rr^2+(Ws-Wr).^2*Lr^2);
Zd=Rs+Ws.*(Ws-Wr)*Lm^2*Rr./Den;
Zq=Ws*Ls-Ws*Lr.*(Ws-Wr).^2*Lm^2./Den;
ax1=subplot(2,2,3);
yyaxis(ax1,'left');
plot(ax1,Ws,Zd-Rs);
title('{\omega_r}=1,{R_r}=0.02');
xlabel('{\omega_s}');
ylabel('Z_d-R_s');
yyaxis(ax1,'right');
plot(ax1,Ws,Zq);
ylabel('Z_q');
grid on;

Wr=-1;
Den=(Rr^2+(Ws-Wr).^2*Lr^2);
Zd=Rs+Ws.*(Ws-Wr)*Lm^2*Rr./Den;
Zq=Ws*Ls-Ws*Lr.*(Ws-Wr).^2*Lm^2./Den;
ax1=subplot(2,2,4);
yyaxis(ax1,'left');
plot(ax1,Ws,Zd-Rs);
title('{\omega_r}=-0.5,{R_r}=0.02');
xlabel('{\omega_s}');
ylabel('Z_d-R_s');
yyaxis(ax1,'right');
plot(ax1,Ws,Zq);
ylabel('Z_q');
grid on;

figure(2);
Wr=0.5;
Den=(Rr^2+(Ws-Wr).^2*Lr^2);
Zd=Rs+Ws.*(Ws-Wr)*Lm^2*Rr./Den;
Zq=Ws*Ls-Ws*Lr.*(Ws-Wr).^2*Lm^2./Den;
Zin=(Zd-Rs) + 1j*Zq;
ZinMag=abs(Zin);
ZinAngle=angle(Zin)*180/pi;
subplot(2,1,1);
plot(Ws,ZinMag);
grid on;
subplot(2,1,2);
plot(Ws,ZinAngle);
axis([-inf,inf,-90,150]);
axis tight;
grid on;

figure(3);
Yin=1./Zin;
YinReal=real(Yin.*Ws);
YinIm=imag(Yin.*Ws);
plot(Ws,YinReal,Ws,YinIm);
grid on;

figure(4);
Zde_fix=((Zd-Rs).*Zq)./ZinMag;
plot(Ws,Zd-Rs,Ws,Zde_fix);

figure(5);
Wa=linspace(1e-3,10,10000);
s=1j*Wa;
lgStr=[];
n=1;
for Ws=0:0.2:1
    Wsl=Ws-Wr;
    G1=Rs+(s+1j*Ws)*Ls;
    G2=(s+1j*Ws)*(Lm^2)./(Lr+Rr./(s+1j*Wsl));
    Gin=1./(G1-G2);
    GinMag=20*log(abs(Gin));
    GinAngle=angle(Gin)*180/pi;
    ax1=subplot(2,1,1);
    semilogx(Wa,GinMag); grid on;hold on;
    ax2=subplot(2,1,2);
    semilogx(Wa,GinAngle); grid on;hold on;
    lgStr{n}=strcat('Ws=',num2str(Ws));n=n+1;
end
legend(ax1,lgStr);
legend(ax2,lgStr);

figure(6);
Ws=linspace(1e-3,10,10000);
lgStr=[];
n=1;
for Wr=0:0.2:1
    s=1j*Ws;
    Wsl=Ws-Wr;
    G1=Rs+(s+1j*Ws)*Ls;
    G2=(s+1j*Ws)*(Lm^2)./(Lr+Rr./(s+1j*Wsl));
    Gin=1./(G1-G2);
    GinMag=20*log(abs(Gin));
    GinAngle=angle(Gin)*180/pi;
    ax1=subplot(2,1,1);
    semilogx(Ws,GinMag); grid on;;hold on;
    ax2=subplot(2,1,2);
    semilogx(Ws,GinAngle); grid on;hold on;
    lgStr{n}=strcat('Wr=',num2str(Wr));n=n+1;
end
legend(ax1,lgStr);
legend(ax2,lgStr);

% figure(7);
% Wr=0.5;
% Ws=linspace(-2,2,1000);
% Den1=Rr^2+Lr^2*(Ws-Wr).^2;
% DZd1=Lm^2*Rr*Ws./Den1;
% DZd2=Lm^2*Rr*(Wr-Ws)./Den1;
% DZd3=2*Lm^2*Lr^2*Rr*Ws.*(Wr-Ws)./(Den1.^2);
% DZd=DZd1-DZd2-DZd3;
% Den=(Rr^2+(Ws-Wr).^2*Lr^2);
% Zd=Rs+Ws.*(Ws-Wr)*Lm^2*Rr./Den;
% Zq=Ws*Ls-Ws*Lr.*(Ws-Wr).^2*Lm^2./Den;
% plot(Ws,Zd,Ws,DZd);