clc;clear;close;
Ws=linspace(-2,2,10000);
Wr=0.05;
Rs=100/4096;
Rr=81/4096;
Lm=5793/4096;
Lls=262/4096;
Llr=Lls;
Ls=Lm+Lls;
Lr=Lm+Llr;
Den=(Rr^2+(Ws-Wr).^2*Lr^2);
Zd=Rs+Ws.*(Ws-Wr)*Lm^2*Rr./Den;
Zq=Ws*Ls-Ws*Lr.*(Ws-Wr).^2*Lm^2./Den;
figure(1);

ax1=subplot(2,2,1);
yyaxis(ax1,'left');
plot(ax1,Ws,Zd-Rs);
title('{\omega_r}=0.05,{R_r}=0.02');
xlabel('{\omega_s}');
ylabel('Z_d-R_s');
yyaxis(ax1,'right');
plot(ax1,Ws,Zq);
ylabel('Z_q');
grid on;

Wr=0.5;
Den=(Rr^2+(Ws-Wr).^2*Lr^2);
Zd=Rs+Ws.*(Ws-Wr)*Lm^2*Rr./Den;
Zq=Ws*Ls-Ws*Lr.*(Ws-Wr).^2*Lm^2./Den;
ax1=subplot(2,2,2);
yyaxis(ax1,'left');
plot(ax1,Ws,Zd-Rs);
hold on;
plot(ax1,Ws,Zd);
title('{\omega_r}=0.5,{R_r}=0.02');
xlabel('{\omega_s}');
ylabel('Z_d-R_s');
yyaxis(ax1,'right');
plot(ax1,Ws,Zq);
ylabel('Z_q');
grid on;

Wr=1;
Den=(Rr^2+(Ws-Wr).^2*Lr^2);
Zd=Rs+Ws.*(Ws-Wr)*Lm^2*Rr./Den;
Zq=Ws*Ls-Ws*Lr.*(Ws-Wr).^2*Lm^2./Den;
ax1=subplot(2,2,3);
yyaxis(ax1,'left');
plot(ax1,Ws,Zd-Rs);
title('{\omega_r}=1,{R_r}=0.02');
xlabel('{\omega_s}');
ylabel('Z_d-R_s');
yyaxis(ax1,'right');
plot(ax1,Ws,Zq);
ylabel('Z_q');
grid on;

Wr=-0.5;
Den=(Rr^2+(Ws-Wr).^2*Lr^2);
Zd=Rs+Ws.*(Ws-Wr)*Lm^2*Rr./Den;
Zq=Ws*Ls-Ws*Lr.*(Ws-Wr).^2*Lm^2./Den;
ax1=subplot(2,2,4);
yyaxis(ax1,'left');
plot(ax1,Ws,Zd-Rs);
title('{\omega_r}=-0.5,{R_r}=0.02');
xlabel('{\omega_s}');
ylabel('Z_d-R_s');
yyaxis(ax1,'right');
plot(ax1,Ws,Zq);
ylabel('Z_q');
grid on;

figure(2);
